name: 'eptech-prod'
services:
  nginx-react-ui:
    build:
      dockerfile: './react-ui/Dockerfile'
    ports:
      - '127.0.0.1:8000:8000'
    restart: 'unless-stopped'

  rest-api:
    build:
      context: './rest-api'
    environment:
      postgres__host: 'db'
      postgres__db: '${POSTGRES_DB?add POSTGRES_DB to .env file}'
      postgres__username: '${POSTGRES_USER?add POSTGRES_USER to .env file}'
      postgres__password: '${POSTGRES_PASSWORD?add POSTGRES_PASSWORD to .env file}'
    restart: 'unless-stopped'
    tty: true

  db:
    image: 'postgres'
    volumes:
      - type: 'volume'
        source: 'postgres-data'
        target: '/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${POSTGRES_DB?add POSTGRES_DB to .env file}'
      POSTGRES_USER: '${POSTGRES_USER?add POSTGRES_USER to .env file}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD?add POSTGRES_PASSWORD to .env file}'
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  postgres-data:
